version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/ciroque/slack-random-emo
    steps:
      - checkout

      - run: go get -v -t -d ./...
      - run: go test -v ./...

      # all steps after this run in the remote environment
      - type: setup-docker-engine
        reusable: true
        version: 17.06.0-ce

      - run:
          name: Install Docker client
          command: |
            apk add curl
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build docker image and publish image tagged with commit
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker build -t ciroque/$CIRCLE_PROJECT_REPONAME:latest .
            docker push ciroque/slack-random-emo:latest
